import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'vbaraznovsky' at '30.04.16 19:13' with Gradle 2.9
 *
 * @author vbaraznovsky, @date 30.04.16 19:13
 */
public class LibraryTest {
    @Test public void testScan() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
